name: "hifigan"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "mel"
    data_type: TYPE_FP32
    dims: [80, 661]
  }
]
output [
  {
    name: "audio"
    data_type: TYPE_FP32
    dims: [1, 169216]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
