model_config:
  fastpitch:
    # io parameters
    n_mel_channels: 80
    # max_seq_len: 2048
    # symbol parameters
    n_symbols: 148
    padding_idx: 0
    symbols_embedding_dim: 384
    # Input FFT parameters
    in_fft_n_layers: 6
    in_fft_n_heads: 1
    in_fft_d_head: 64
    in_fft_conv1d_filter_size: 1536
    in_fft_conv1d_kernel_size: 3
    in_fft_output_size: 384
    p_in_fft_dropout: 0.1
    p_in_fft_dropatt: 0.1
    p_in_fft_dropemb: 0.0
    # Output FFT parameters
    out_fft_n_layers: 6
    out_fft_n_heads: 1
    out_fft_d_head: 64
    out_fft_conv1d_kernel_size: 3
    out_fft_conv1d_filter_size: 1536
    out_fft_output_size: 384
    p_out_fft_dropout: 0.1
    p_out_fft_dropatt: 0.1
    p_out_fft_dropemb: 0.0
    # Duration predictor parameters
    dur_predictor_kernel_size: 3
    dur_predictor_filter_size: 256
    p_dur_predictor_dropout: 0.1
    dur_predictor_n_layers: 2
    # Pitch predictor parameters
    pitch_predictor_kernel_size: 3
    pitch_predictor_filter_size: 256
    p_pitch_predictor_dropout: 0.1
    pitch_predictor_n_layers: 2
    # Energy predictor parameters
    energy_predictor_kernel_size: 3
    energy_predictor_filter_size: 256
    p_energy_predictor_dropout: 0.1
    energy_predictor_n_layers: 2
    # Pitch & Energy Conditioning parameters
    energy_conditioning: True
    pitch_embedding_kernel_size: 3
    energy_embedding_kernel_size: 3
    # Speaker Parameters
    n_speakers: 1
    speaker_emb_weight: 1.0
  hifigan:
    upsample_rates: [8, 8, 2, 2]
    upsample_kernel_sizes: [16, 16, 4, 4]
    upsample_initial_channel: 512
    resblock: "1"
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes:
      - [1, 3, 5]
      - [1, 3, 5]
      - [1, 3, 5]

inference:
  input_file: "phrases/devset10.tsv"
  output_dir: "output"
  use_amp: True
  use_cuda: True
  batch_size: 32
  warmup_steps: 3
  num_repeats: 10
  use_cudnn_benchmark: True
  denoising_strength: 0.00
  speaker_id: 0
  pace: 1.0
  p_arpabet: 1.0
  max_wav_value: 32768.0
  sampling_rate: 22050
  window_length: 1024
  hop_length: 256
  fade_out: 10
  affinity: "single"
  l2_promote: True
  hifigan: "pretrained_models/hifigan/hifigan_gen_checkpoint_10000_ft.pt"
  fastpitch: "pretrained_models/fastpitch/nvidia_fastpitch_210824.pt"
  symbol_set: "english_basic"
  text_cleaners: ["english_cleaners_v2"]
  cmudict_path: "cmudict/cmudict-0.7b"
  heteronyms_path: "cmudict/heteronyms"
