# FROM nvcr.io/nvidia/pytorch:24.08-py3
FROM nvcr.io/nvidia/tensorrt:24.08-py3

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /home/


#RUN apt-get update && \
#    apt-get install -y git

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
