version: '3'

services:
  dev:
    container_name: dev

    stdin_open: true # docker run -i
    tty: true # docker run -t

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7008:7008"

    volumes:
      - type: bind
        source: .
        target: /home/

    networks:
      - default_network

    deploy:
      resources:
        limits:
          memory: 12g
        reservations:
          devices:
            - capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_DRIVER_CAPABILITIES=all
      # - MLFLOW_TRACKING_URI=/share/sections/perception/work/DeltaNet/training_logs/mlruns/
    shm_size: "8gb"

networks:
  default_network:
