services:
  dev:
    container_name: dev

    stdin_open: true # docker run -i
    tty: true # docker run -t

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7008:7008"

    volumes:
      - type: bind
        source: .
        target: /home/

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_DRIVER_CAPABILITIES=all

    shm_size: "8gb"
