name: "fastpitch"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "text"
    data_type: TYPE_INT64
    dims: [ 122 ]
  },
  {
    name: "pace"
    data_type: TYPE_FP64
    dims: [ 1 ]
  }
]
output [
  {
    name: "mel"
    data_type: TYPE_FP32
    dims: [ 80, -1]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
